package com.xforceplus.ultraman.permissions.repository.entity;

import java.io.Serializable;

public class DataScopeSubCondition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.conditions_id
     *
     * @mbg.generated
     */
    private Long conditionsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.value_type_id
     *
     * @mbg.generated
     */
    private Long valueTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.index
     *
     * @mbg.generated
     */
    private Short index;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.link
     *
     * @mbg.generated
     */
    private Byte link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.id
     *
     * @return the value of data_scope_sub_condition.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.id
     *
     * @param id the value for data_scope_sub_condition.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.conditions_id
     *
     * @return the value of data_scope_sub_condition.conditions_id
     *
     * @mbg.generated
     */
    public Long getConditionsId() {
        return conditionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.conditions_id
     *
     * @param conditionsId the value for data_scope_sub_condition.conditions_id
     *
     * @mbg.generated
     */
    public void setConditionsId(Long conditionsId) {
        this.conditionsId = conditionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.value_type_id
     *
     * @return the value of data_scope_sub_condition.value_type_id
     *
     * @mbg.generated
     */
    public Long getValueTypeId() {
        return valueTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.value_type_id
     *
     * @param valueTypeId the value for data_scope_sub_condition.value_type_id
     *
     * @mbg.generated
     */
    public void setValueTypeId(Long valueTypeId) {
        this.valueTypeId = valueTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.operator
     *
     * @return the value of data_scope_sub_condition.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.operator
     *
     * @param operator the value for data_scope_sub_condition.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.index
     *
     * @return the value of data_scope_sub_condition.index
     *
     * @mbg.generated
     */
    public Short getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.index
     *
     * @param index the value for data_scope_sub_condition.index
     *
     * @mbg.generated
     */
    public void setIndex(Short index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.value
     *
     * @return the value of data_scope_sub_condition.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.value
     *
     * @param value the value for data_scope_sub_condition.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.link
     *
     * @return the value of data_scope_sub_condition.link
     *
     * @mbg.generated
     */
    public Byte getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.link
     *
     * @param link the value for data_scope_sub_condition.link
     *
     * @mbg.generated
     */
    public void setLink(Byte link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DataScopeSubCondition other = (DataScopeSubCondition) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getConditionsId() == null ? other.getConditionsId() == null : this.getConditionsId().equals(other.getConditionsId()))
            && (this.getValueTypeId() == null ? other.getValueTypeId() == null : this.getValueTypeId().equals(other.getValueTypeId()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
            && (this.getIndex() == null ? other.getIndex() == null : this.getIndex().equals(other.getIndex()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getLink() == null ? other.getLink() == null : this.getLink().equals(other.getLink()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getConditionsId() == null) ? 0 : getConditionsId().hashCode());
        result = prime * result + ((getValueTypeId() == null) ? 0 : getValueTypeId().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getIndex() == null) ? 0 : getIndex().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getLink() == null) ? 0 : getLink().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", conditionsId=").append(conditionsId);
        sb.append(", valueTypeId=").append(valueTypeId);
        sb.append(", operator=").append(operator);
        sb.append(", index=").append(index);
        sb.append(", value=").append(value);
        sb.append(", link=").append(link);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}