package com.xforceplus.ultraman.permissions.repository.entity;

import java.io.Serializable;

public class DataScope implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope.entity
     *
     * @mbg.generated
     */
    private String entity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_scope
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope.id
     *
     * @return the value of data_scope.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope.id
     *
     * @param id the value for data_scope.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope.entity
     *
     * @return the value of data_scope.entity
     *
     * @mbg.generated
     */
    public String getEntity() {
        return entity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope.entity
     *
     * @param entity the value for data_scope.entity
     *
     * @mbg.generated
     */
    public void setEntity(String entity) {
        this.entity = entity == null ? null : entity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DataScope other = (DataScope) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEntity() == null ? other.getEntity() == null : this.getEntity().equals(other.getEntity()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEntity() == null) ? 0 : getEntity().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", entity=").append(entity);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}