package com.xforceplus.ultraman.permissions.rule.repository;

import com.xforceplus.ultraman.permissions.rule.repository.entity.DataScope;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DataScopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope
     *
     * @mbg.generated
     */
    int insert(DataScope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope
     *
     * @mbg.generated
     */
    DataScope selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope
     *
     * @mbg.generated
     */
    List<DataScope> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataScope record);
}