package com.xforceplus.ultraman.permissions.rule.repository;

import com.xforceplus.ultraman.permissions.rule.repository.entity.DataScopeConditions;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DataScopeConditionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_conditions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_conditions
     *
     * @mbg.generated
     */
    int insert(DataScopeConditions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_conditions
     *
     * @mbg.generated
     */
    DataScopeConditions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_conditions
     *
     * @mbg.generated
     */
    List<DataScopeConditions> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_conditions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataScopeConditions record);
}