package com.xforceplus.ultraman.permissions.rule.repository;

import com.xforceplus.ultraman.permissions.rule.repository.entity.DataScopeSubCondition;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DataScopeSubConditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    int insert(DataScopeSubCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    DataScopeSubCondition selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    List<DataScopeSubCondition> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataScopeSubCondition record);
}