spring:
  profiles:
    active: dev
management:
  health:
    redis:
      enabled: false
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    shutdown:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true