// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ForStatment.proto

package com.xforceplus.ultraman.permissions.transfer.grpc.generate;

public final class ForStatmentGrpc {
  private ForStatmentGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StatmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xforceplus.ultraman.permissions.Statment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 当前需要运行的 sql.
     * </pre>
     *
     * <code>string sql = 1;</code>
     */
    String getSql();
    /**
     * <pre>
     * 当前需要运行的 sql.
     * </pre>
     *
     * <code>string sql = 1;</code>
     */
    com.google.protobuf.ByteString
        getSqlBytes();

    /**
     * <pre>
     * 当前授权信息.
     * </pre>
     *
     * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
     */
    java.util.List<AuthorizationGrpc.Authorization>
        getAuthorizationList();
    /**
     * <pre>
     * 当前授权信息.
     * </pre>
     *
     * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
     */
    AuthorizationGrpc.Authorization getAuthorization(int index);
    /**
     * <pre>
     * 当前授权信息.
     * </pre>
     *
     * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
     */
    int getAuthorizationCount();
    /**
     * <pre>
     * 当前授权信息.
     * </pre>
     *
     * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
     */
    java.util.List<? extends AuthorizationGrpc.AuthorizationOrBuilder>
        getAuthorizationOrBuilderList();
    /**
     * <pre>
     * 当前授权信息.
     * </pre>
     *
     * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
     */
    AuthorizationGrpc.AuthorizationOrBuilder getAuthorizationOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.xforceplus.ultraman.permissions.Statment}
   */
  public  static final class Statment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xforceplus.ultraman.permissions.Statment)
      StatmentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Statment.newBuilder() to construct.
    private Statment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Statment() {
      sql_ = "";
      authorization_ = java.util.Collections.emptyList();
    }

      @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Statment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
          throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
                String s = input.readStringRequireUtf8();

              sql_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  authorization_ = new java.util.ArrayList<AuthorizationGrpc.Authorization>();
                mutable_bitField0_ |= 0x00000002;
              }
              authorization_.add(
                  input.readMessage(AuthorizationGrpc.Authorization.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          authorization_ = java.util.Collections.unmodifiableList(authorization_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
        return ForStatmentGrpc.internal_static_com_xforceplus_ultraman_permissions_Statment_descriptor;
    }

      protected FieldAccessorTable
        internalGetFieldAccessorTable() {
          return ForStatmentGrpc.internal_static_com_xforceplus_ultraman_permissions_Statment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Statment.class, Builder.class);
    }

    private int bitField0_;
    public static final int SQL_FIELD_NUMBER = 1;
      private volatile Object sql_;
    /**
     * <pre>
     * 当前需要运行的 sql.
     * </pre>
     *
     * <code>string sql = 1;</code>
     */
    public String getSql() {
        Object ref = sql_;
        if (ref instanceof String) {
            return (String) ref;
      } else {
            com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
        sql_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 当前需要运行的 sql.
     * </pre>
     *
     * <code>string sql = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSqlBytes() {
        Object ref = sql_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sql_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHORIZATION_FIELD_NUMBER = 2;
      private java.util.List<AuthorizationGrpc.Authorization> authorization_;
    /**
     * <pre>
     * 当前授权信息.
     * </pre>
     *
     * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
     */
    public java.util.List<AuthorizationGrpc.Authorization> getAuthorizationList() {
      return authorization_;
    }
    /**
     * <pre>
     * 当前授权信息.
     * </pre>
     *
     * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
     */
    public java.util.List<? extends AuthorizationGrpc.AuthorizationOrBuilder>
        getAuthorizationOrBuilderList() {
      return authorization_;
    }
    /**
     * <pre>
     * 当前授权信息.
     * </pre>
     *
     * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
     */
    public int getAuthorizationCount() {
      return authorization_.size();
    }
    /**
     * <pre>
     * 当前授权信息.
     * </pre>
     *
     * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
     */
    public AuthorizationGrpc.Authorization getAuthorization(int index) {
      return authorization_.get(index);
    }
    /**
     * <pre>
     * 当前授权信息.
     * </pre>
     *
     * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
     */
    public AuthorizationGrpc.AuthorizationOrBuilder getAuthorizationOrBuilder(
        int index) {
      return authorization_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSqlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sql_);
      }
      for (int i = 0; i < authorization_.size(); i++) {
        output.writeMessage(2, authorization_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSqlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sql_);
      }
      for (int i = 0; i < authorization_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, authorization_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

      @Override
      public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
          if (!(obj instanceof Statment)) {
        return super.equals(obj);
      }
          Statment other = (Statment) obj;

      boolean result = true;
      result = result && getSql()
          .equals(other.getSql());
      result = result && getAuthorizationList()
          .equals(other.getAuthorizationList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

      @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SQL_FIELD_NUMBER;
      hash = (53 * hash) + getSql().hashCode();
      if (getAuthorizationCount() > 0) {
        hash = (37 * hash) + AUTHORIZATION_FIELD_NUMBER;
        hash = (53 * hash) + getAuthorizationList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

      public static Statment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

      public static Statment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

      public static Statment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

      public static Statment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

      public static Statment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

      public static Statment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

      public static Statment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

      public static Statment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

      public static Statment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

      public static Statment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

      public static Statment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

      public static Statment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

      public static Builder newBuilder(Statment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

      @Override
    protected Builder newBuilderForType(
          BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xforceplus.ultraman.permissions.Statment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xforceplus.ultraman.permissions.Statment)
        StatmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
          return ForStatmentGrpc.internal_static_com_xforceplus_ultraman_permissions_Statment_descriptor;
      }

        protected FieldAccessorTable
          internalGetFieldAccessorTable() {
            return ForStatmentGrpc.internal_static_com_xforceplus_ultraman_permissions_Statment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Statment.class, Builder.class);
      }

      // Construct using com.xforceplus.ultraman.permissions.transfer.grpc.generate.ForStatmentGrpc.Statment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAuthorizationFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        sql_ = "";

        if (authorizationBuilder_ == null) {
          authorization_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          authorizationBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
          return ForStatmentGrpc.internal_static_com_xforceplus_ultraman_permissions_Statment_descriptor;
      }

        public Statment getDefaultInstanceForType() {
            return Statment.getDefaultInstance();
      }

        public Statment build() {
            Statment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

        public Statment buildPartial() {
            Statment result = new Statment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.sql_ = sql_;
        if (authorizationBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            authorization_ = java.util.Collections.unmodifiableList(authorization_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.authorization_ = authorization_;
        } else {
          result.authorization_ = authorizationBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Statment) {
              return mergeFrom((Statment) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

        public Builder mergeFrom(Statment other) {
            if (other == Statment.getDefaultInstance()) return this;
        if (!other.getSql().isEmpty()) {
          sql_ = other.sql_;
          onChanged();
        }
        if (authorizationBuilder_ == null) {
          if (!other.authorization_.isEmpty()) {
            if (authorization_.isEmpty()) {
              authorization_ = other.authorization_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAuthorizationIsMutable();
              authorization_.addAll(other.authorization_);
            }
            onChanged();
          }
        } else {
          if (!other.authorization_.isEmpty()) {
            if (authorizationBuilder_.isEmpty()) {
              authorizationBuilder_.dispose();
              authorizationBuilder_ = null;
              authorization_ = other.authorization_;
              bitField0_ = (bitField0_ & ~0x00000002);
                authorizationBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAuthorizationFieldBuilder() : null;
            } else {
              authorizationBuilder_.addAllMessages(other.authorization_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
          Statment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Statment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

        private Object sql_ = "";
      /**
       * <pre>
       * 当前需要运行的 sql.
       * </pre>
       *
       * <code>string sql = 1;</code>
       */
      public String getSql() {
          Object ref = sql_;
          if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
              String s = bs.toStringUtf8();
          sql_ = s;
          return s;
        } else {
              return (String) ref;
        }
      }
      /**
       * <pre>
       * 当前需要运行的 sql.
       * </pre>
       *
       * <code>string sql = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSqlBytes() {
          Object ref = sql_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sql_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 当前需要运行的 sql.
       * </pre>
       *
       * <code>string sql = 1;</code>
       */
      public Builder setSql(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        sql_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前需要运行的 sql.
       * </pre>
       *
       * <code>string sql = 1;</code>
       */
      public Builder clearSql() {

        sql_ = getDefaultInstance().getSql();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前需要运行的 sql.
       * </pre>
       *
       * <code>string sql = 1;</code>
       */
      public Builder setSqlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        sql_ = value;
        onChanged();
        return this;
      }

        private java.util.List<AuthorizationGrpc.Authorization> authorization_ =
        java.util.Collections.emptyList();
      private void ensureAuthorizationIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            authorization_ = new java.util.ArrayList<AuthorizationGrpc.Authorization>(authorization_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AuthorizationGrpc.Authorization, AuthorizationGrpc.Authorization.Builder, AuthorizationGrpc.AuthorizationOrBuilder> authorizationBuilder_;

      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public java.util.List<AuthorizationGrpc.Authorization> getAuthorizationList() {
        if (authorizationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(authorization_);
        } else {
          return authorizationBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public int getAuthorizationCount() {
        if (authorizationBuilder_ == null) {
          return authorization_.size();
        } else {
          return authorizationBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public AuthorizationGrpc.Authorization getAuthorization(int index) {
        if (authorizationBuilder_ == null) {
          return authorization_.get(index);
        } else {
          return authorizationBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public Builder setAuthorization(
          int index, AuthorizationGrpc.Authorization value) {
        if (authorizationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuthorizationIsMutable();
          authorization_.set(index, value);
          onChanged();
        } else {
          authorizationBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public Builder setAuthorization(
          int index, AuthorizationGrpc.Authorization.Builder builderForValue) {
        if (authorizationBuilder_ == null) {
          ensureAuthorizationIsMutable();
          authorization_.set(index, builderForValue.build());
          onChanged();
        } else {
          authorizationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public Builder addAuthorization(AuthorizationGrpc.Authorization value) {
        if (authorizationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuthorizationIsMutable();
          authorization_.add(value);
          onChanged();
        } else {
          authorizationBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public Builder addAuthorization(
          int index, AuthorizationGrpc.Authorization value) {
        if (authorizationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuthorizationIsMutable();
          authorization_.add(index, value);
          onChanged();
        } else {
          authorizationBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public Builder addAuthorization(
          AuthorizationGrpc.Authorization.Builder builderForValue) {
        if (authorizationBuilder_ == null) {
          ensureAuthorizationIsMutable();
          authorization_.add(builderForValue.build());
          onChanged();
        } else {
          authorizationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public Builder addAuthorization(
          int index, AuthorizationGrpc.Authorization.Builder builderForValue) {
        if (authorizationBuilder_ == null) {
          ensureAuthorizationIsMutable();
          authorization_.add(index, builderForValue.build());
          onChanged();
        } else {
          authorizationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public Builder addAllAuthorization(
          Iterable<? extends AuthorizationGrpc.Authorization> values) {
        if (authorizationBuilder_ == null) {
          ensureAuthorizationIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, authorization_);
          onChanged();
        } else {
          authorizationBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public Builder clearAuthorization() {
        if (authorizationBuilder_ == null) {
          authorization_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          authorizationBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public Builder removeAuthorization(int index) {
        if (authorizationBuilder_ == null) {
          ensureAuthorizationIsMutable();
          authorization_.remove(index);
          onChanged();
        } else {
          authorizationBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public AuthorizationGrpc.Authorization.Builder getAuthorizationBuilder(
          int index) {
        return getAuthorizationFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public AuthorizationGrpc.AuthorizationOrBuilder getAuthorizationOrBuilder(
          int index) {
        if (authorizationBuilder_ == null) {
          return authorization_.get(index);  } else {
          return authorizationBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public java.util.List<? extends AuthorizationGrpc.AuthorizationOrBuilder>
           getAuthorizationOrBuilderList() {
        if (authorizationBuilder_ != null) {
          return authorizationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(authorization_);
        }
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public AuthorizationGrpc.Authorization.Builder addAuthorizationBuilder() {
        return getAuthorizationFieldBuilder().addBuilder(
            AuthorizationGrpc.Authorization.getDefaultInstance());
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public AuthorizationGrpc.Authorization.Builder addAuthorizationBuilder(
          int index) {
        return getAuthorizationFieldBuilder().addBuilder(
            index, AuthorizationGrpc.Authorization.getDefaultInstance());
      }
      /**
       * <pre>
       * 当前授权信息.
       * </pre>
       *
       * <code>repeated .com.xforceplus.ultraman.permissions.Authorization authorization = 2;</code>
       */
      public java.util.List<AuthorizationGrpc.Authorization.Builder>
           getAuthorizationBuilderList() {
        return getAuthorizationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AuthorizationGrpc.Authorization, AuthorizationGrpc.Authorization.Builder, AuthorizationGrpc.AuthorizationOrBuilder>
          getAuthorizationFieldBuilder() {
        if (authorizationBuilder_ == null) {
          authorizationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AuthorizationGrpc.Authorization, AuthorizationGrpc.Authorization.Builder, AuthorizationGrpc.AuthorizationOrBuilder>(
                  authorization_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          authorization_ = null;
        }
        return authorizationBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xforceplus.ultraman.permissions.Statment)
    }

    // @@protoc_insertion_point(class_scope:com.xforceplus.ultraman.permissions.Statment)
    private static final Statment DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new Statment();
    }

      public static Statment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Statment>
        PARSER = new com.google.protobuf.AbstractParser<Statment>() {
      public Statment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Statment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Statment> parser() {
      return PARSER;
    }

      @Override
    public com.google.protobuf.Parser<Statment> getParserForType() {
      return PARSER;
    }

      public Statment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StatmentResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xforceplus.ultraman.permissions.StatmentResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 状态码.
     * </pre>
     *
     * <code>int32 status = 1;</code>
     */
    int getStatus();

    /**
     * <pre>
     * 如果状态为 UPDATE,那么此为新的语句.
     * </pre>
     *
     * <code>string newSql = 2;</code>
     */
    String getNewSql();
    /**
     * <pre>
     * 如果状态为 UPDATE,那么此为新的语句.
     * </pre>
     *
     * <code>string newSql = 2;</code>
     */
    com.google.protobuf.ByteString
        getNewSqlBytes();

    /**
     * <pre>
     * 需要隐藏的字段.
     * </pre>
     *
     * <code>repeated string backList = 3;</code>
     */
    java.util.List<String>
        getBackListList();
    /**
     * <pre>
     * 需要隐藏的字段.
     * </pre>
     *
     * <code>repeated string backList = 3;</code>
     */
    int getBackListCount();
    /**
     * <pre>
     * 需要隐藏的字段.
     * </pre>
     *
     * <code>repeated string backList = 3;</code>
     */
    String getBackList(int index);
    /**
     * <pre>
     * 需要隐藏的字段.
     * </pre>
     *
     * <code>repeated string backList = 3;</code>
     */
    com.google.protobuf.ByteString
        getBackListBytes(int index);

    /**
     * <pre>
     * 响应的消息.
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    String getMessage();
    /**
     * <pre>
     * 响应的消息.
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code com.xforceplus.ultraman.permissions.StatmentResult}
   */
  public  static final class StatmentResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xforceplus.ultraman.permissions.StatmentResult)
      StatmentResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StatmentResult.newBuilder() to construct.
    private StatmentResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StatmentResult() {
      status_ = 0;
      newSql_ = "";
      backList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      message_ = "";
    }

      @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StatmentResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
          throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              status_ = input.readInt32();
              break;
            }
            case 18: {
                String s = input.readStringRequireUtf8();

              newSql_ = s;
              break;
            }
            case 26: {
                String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                backList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              backList_.add(s);
              break;
            }
            case 34: {
                String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          backList_ = backList_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
        return ForStatmentGrpc.internal_static_com_xforceplus_ultraman_permissions_StatmentResult_descriptor;
    }

      protected FieldAccessorTable
        internalGetFieldAccessorTable() {
          return ForStatmentGrpc.internal_static_com_xforceplus_ultraman_permissions_StatmentResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StatmentResult.class, Builder.class);
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <pre>
     * 状态码.
     * </pre>
     *
     * <code>int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int NEWSQL_FIELD_NUMBER = 2;
      private volatile Object newSql_;
    /**
     * <pre>
     * 如果状态为 UPDATE,那么此为新的语句.
     * </pre>
     *
     * <code>string newSql = 2;</code>
     */
    public String getNewSql() {
        Object ref = newSql_;
        if (ref instanceof String) {
            return (String) ref;
      } else {
            com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
        newSql_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 如果状态为 UPDATE,那么此为新的语句.
     * </pre>
     *
     * <code>string newSql = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNewSqlBytes() {
        Object ref = newSql_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        newSql_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BACKLIST_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList backList_;
    /**
     * <pre>
     * 需要隐藏的字段.
     * </pre>
     *
     * <code>repeated string backList = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getBackListList() {
      return backList_;
    }
    /**
     * <pre>
     * 需要隐藏的字段.
     * </pre>
     *
     * <code>repeated string backList = 3;</code>
     */
    public int getBackListCount() {
      return backList_.size();
    }
    /**
     * <pre>
     * 需要隐藏的字段.
     * </pre>
     *
     * <code>repeated string backList = 3;</code>
     */
    public String getBackList(int index) {
      return backList_.get(index);
    }
    /**
     * <pre>
     * 需要隐藏的字段.
     * </pre>
     *
     * <code>repeated string backList = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBackListBytes(int index) {
      return backList_.getByteString(index);
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
      private volatile Object message_;
    /**
     * <pre>
     * 响应的消息.
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    public String getMessage() {
        Object ref = message_;
        if (ref instanceof String) {
            return (String) ref;
      } else {
            com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 响应的消息.
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != 0) {
        output.writeInt32(1, status_);
      }
      if (!getNewSqlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, newSql_);
      }
      for (int i = 0; i < backList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, backList_.getRaw(i));
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (!getNewSqlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, newSql_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < backList_.size(); i++) {
          dataSize += computeStringSizeNoTag(backList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getBackListList().size();
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

      @Override
      public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
          if (!(obj instanceof StatmentResult)) {
        return super.equals(obj);
      }
          StatmentResult other = (StatmentResult) obj;

      boolean result = true;
      result = result && (getStatus()
          == other.getStatus());
      result = result && getNewSql()
          .equals(other.getNewSql());
      result = result && getBackListList()
          .equals(other.getBackListList());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

      @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + NEWSQL_FIELD_NUMBER;
      hash = (53 * hash) + getNewSql().hashCode();
      if (getBackListCount() > 0) {
        hash = (37 * hash) + BACKLIST_FIELD_NUMBER;
        hash = (53 * hash) + getBackListList().hashCode();
      }
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

      public static StatmentResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

      public static StatmentResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

      public static StatmentResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

      public static StatmentResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

      public static StatmentResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

      public static StatmentResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

      public static StatmentResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

      public static StatmentResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

      public static StatmentResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

      public static StatmentResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

      public static StatmentResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

      public static StatmentResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

      public static Builder newBuilder(StatmentResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

      @Override
    protected Builder newBuilderForType(
          BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xforceplus.ultraman.permissions.StatmentResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xforceplus.ultraman.permissions.StatmentResult)
        StatmentResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
          return ForStatmentGrpc.internal_static_com_xforceplus_ultraman_permissions_StatmentResult_descriptor;
      }

        protected FieldAccessorTable
          internalGetFieldAccessorTable() {
            return ForStatmentGrpc.internal_static_com_xforceplus_ultraman_permissions_StatmentResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StatmentResult.class, Builder.class);
      }

      // Construct using com.xforceplus.ultraman.permissions.transfer.grpc.generate.ForStatmentGrpc.StatmentResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        newSql_ = "";

        backList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
          return ForStatmentGrpc.internal_static_com_xforceplus_ultraman_permissions_StatmentResult_descriptor;
      }

        public StatmentResult getDefaultInstanceForType() {
            return StatmentResult.getDefaultInstance();
      }

        public StatmentResult build() {
            StatmentResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

        public StatmentResult buildPartial() {
            StatmentResult result = new StatmentResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.status_ = status_;
        result.newSql_ = newSql_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          backList_ = backList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.backList_ = backList_;
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof StatmentResult) {
              return mergeFrom((StatmentResult) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

        public Builder mergeFrom(StatmentResult other) {
            if (other == StatmentResult.getDefaultInstance()) return this;
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getNewSql().isEmpty()) {
          newSql_ = other.newSql_;
          onChanged();
        }
        if (!other.backList_.isEmpty()) {
          if (backList_.isEmpty()) {
            backList_ = other.backList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureBackListIsMutable();
            backList_.addAll(other.backList_);
          }
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
          StatmentResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (StatmentResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int status_ ;
      /**
       * <pre>
       * 状态码.
       * </pre>
       *
       * <code>int32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       * 状态码.
       * </pre>
       *
       * <code>int32 status = 1;</code>
       */
      public Builder setStatus(int value) {

        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态码.
       * </pre>
       *
       * <code>int32 status = 1;</code>
       */
      public Builder clearStatus() {

        status_ = 0;
        onChanged();
        return this;
      }

        private Object newSql_ = "";
      /**
       * <pre>
       * 如果状态为 UPDATE,那么此为新的语句.
       * </pre>
       *
       * <code>string newSql = 2;</code>
       */
      public String getNewSql() {
          Object ref = newSql_;
          if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
              String s = bs.toStringUtf8();
          newSql_ = s;
          return s;
        } else {
              return (String) ref;
        }
      }
      /**
       * <pre>
       * 如果状态为 UPDATE,那么此为新的语句.
       * </pre>
       *
       * <code>string newSql = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNewSqlBytes() {
          Object ref = newSql_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          newSql_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 如果状态为 UPDATE,那么此为新的语句.
       * </pre>
       *
       * <code>string newSql = 2;</code>
       */
      public Builder setNewSql(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        newSql_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 如果状态为 UPDATE,那么此为新的语句.
       * </pre>
       *
       * <code>string newSql = 2;</code>
       */
      public Builder clearNewSql() {

        newSql_ = getDefaultInstance().getNewSql();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 如果状态为 UPDATE,那么此为新的语句.
       * </pre>
       *
       * <code>string newSql = 2;</code>
       */
      public Builder setNewSqlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        newSql_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList backList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBackListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          backList_ = new com.google.protobuf.LazyStringArrayList(backList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * 需要隐藏的字段.
       * </pre>
       *
       * <code>repeated string backList = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getBackListList() {
        return backList_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 需要隐藏的字段.
       * </pre>
       *
       * <code>repeated string backList = 3;</code>
       */
      public int getBackListCount() {
        return backList_.size();
      }
      /**
       * <pre>
       * 需要隐藏的字段.
       * </pre>
       *
       * <code>repeated string backList = 3;</code>
       */
      public String getBackList(int index) {
        return backList_.get(index);
      }
      /**
       * <pre>
       * 需要隐藏的字段.
       * </pre>
       *
       * <code>repeated string backList = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBackListBytes(int index) {
        return backList_.getByteString(index);
      }
      /**
       * <pre>
       * 需要隐藏的字段.
       * </pre>
       *
       * <code>repeated string backList = 3;</code>
       */
      public Builder setBackList(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBackListIsMutable();
        backList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 需要隐藏的字段.
       * </pre>
       *
       * <code>repeated string backList = 3;</code>
       */
      public Builder addBackList(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBackListIsMutable();
        backList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 需要隐藏的字段.
       * </pre>
       *
       * <code>repeated string backList = 3;</code>
       */
      public Builder addAllBackList(
          Iterable<String> values) {
        ensureBackListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, backList_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 需要隐藏的字段.
       * </pre>
       *
       * <code>repeated string backList = 3;</code>
       */
      public Builder clearBackList() {
        backList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 需要隐藏的字段.
       * </pre>
       *
       * <code>repeated string backList = 3;</code>
       */
      public Builder addBackListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureBackListIsMutable();
        backList_.add(value);
        onChanged();
        return this;
      }

        private Object message_ = "";
      /**
       * <pre>
       * 响应的消息.
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public String getMessage() {
          Object ref = message_;
          if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
              String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
              return (String) ref;
        }
      }
      /**
       * <pre>
       * 响应的消息.
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
          Object ref = message_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 响应的消息.
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应的消息.
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public Builder clearMessage() {

        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应的消息.
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xforceplus.ultraman.permissions.StatmentResult)
    }

    // @@protoc_insertion_point(class_scope:com.xforceplus.ultraman.permissions.StatmentResult)
    private static final StatmentResult DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new StatmentResult();
    }

      public static StatmentResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StatmentResult>
        PARSER = new com.google.protobuf.AbstractParser<StatmentResult>() {
      public StatmentResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StatmentResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StatmentResult> parser() {
      return PARSER;
    }

      @Override
    public com.google.protobuf.Parser<StatmentResult> getParserForType() {
      return PARSER;
    }

      public StatmentResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code com.xforceplus.ultraman.permissions.StatmentCheckService}
   */
  public static abstract class StatmentCheckService
      implements com.google.protobuf.Service {
    protected StatmentCheckService() {}

    public interface Interface {
      /**
       * <code>rpc check(.com.xforceplus.ultraman.permissions.Statment) returns (.com.xforceplus.ultraman.permissions.StatmentResult);</code>
       */
      public abstract void check(
          com.google.protobuf.RpcController controller,
          Statment request,
          com.google.protobuf.RpcCallback<StatmentResult> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new StatmentCheckService() {
          @Override
        public  void check(
              com.google.protobuf.RpcController controller,
              Statment request,
              com.google.protobuf.RpcCallback<StatmentResult> done) {
          impl.check(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
              throw new IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
                return impl.check(controller, (Statment) request);
            default:
                throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
              throw new IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
                return Statment.getDefaultInstance();
            default:
                throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
              throw new IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
                return StatmentResult.getDefaultInstance();
            default:
                throw new AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc check(.com.xforceplus.ultraman.permissions.Statment) returns (.com.xforceplus.ultraman.permissions.StatmentResult);</code>
     */
    public abstract void check(
        com.google.protobuf.RpcController controller,
        Statment request,
        com.google.protobuf.RpcCallback<StatmentResult> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
        return ForStatmentGrpc.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
            this.check(controller, (Statment) request,
                com.google.protobuf.RpcUtil.<StatmentResult>specializeCallback(
              done));
          return;
        default:
            throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
            return Statment.getDefaultInstance();
        default:
            throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
            return StatmentResult.getDefaultInstance();
        default:
            throw new AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

      public static final class Stub extends StatmentCheckService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void check(
          com.google.protobuf.RpcController controller,
          Statment request,
          com.google.protobuf.RpcCallback<StatmentResult> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
            StatmentResult.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
              StatmentResult.class,
              StatmentResult.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
        public StatmentResult check(
            com.google.protobuf.RpcController controller,
            Statment request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

        public StatmentResult check(
            com.google.protobuf.RpcController controller,
            Statment request)
          throws com.google.protobuf.ServiceException {
            return (StatmentResult) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
                StatmentResult.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:com.xforceplus.ultraman.permissions.StatmentCheckService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xforceplus_ultraman_permissions_Statment_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xforceplus_ultraman_permissions_Statment_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xforceplus_ultraman_permissions_StatmentResult_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xforceplus_ultraman_permissions_StatmentResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
      String[] descriptorData = {
      "\n\021ForStatment.proto\022#com.xforceplus.ultr" +
      "aman.permissions\032\nBase.proto\"b\n\010Statment" +
      "\022\013\n\003sql\030\001 \001(\t\022I\n\rauthorization\030\002 \003(\01322.c" +
      "om.xforceplus.ultraman.permissions.Autho" +
      "rization\"S\n\016StatmentResult\022\016\n\006status\030\001 \001" +
      "(\005\022\016\n\006newSql\030\002 \001(\t\022\020\n\010backList\030\003 \003(\t\022\017\n\007" +
      "message\030\004 \001(\t2\203\001\n\024StatmentCheckService\022k" +
      "\n\005check\022-.com.xforceplus.ultraman.permis" +
      "sions.Statment\0323.com.xforceplus.ultraman" +
      ".permissions.StatmentResultBR\n:com.xforc" +
      "eplus.ultraman.permissions.transfer.grpc" +
      ".generateB\017ForStatmentGrpcH\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
            AuthorizationGrpc.getDescriptor(),
        }, assigner);
    internal_static_com_xforceplus_ultraman_permissions_Statment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xforceplus_ultraman_permissions_Statment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xforceplus_ultraman_permissions_Statment_descriptor,
        new String[]{"Sql", "Authorization",});
    internal_static_com_xforceplus_ultraman_permissions_StatmentResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xforceplus_ultraman_permissions_StatmentResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xforceplus_ultraman_permissions_StatmentResult_descriptor,
        new String[]{"Status", "NewSql", "BackList", "Message",});
      AuthorizationGrpc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
