package com.xforceplus.ultraman.permissions.repository;

import com.xforceplus.ultraman.permissions.repository.entity.DataScopeSubCondition;
import com.xforceplus.ultraman.permissions.repository.entity.DataScopeSubConditionExample.Criteria;
import com.xforceplus.ultraman.permissions.repository.entity.DataScopeSubConditionExample.Criterion;
import com.xforceplus.ultraman.permissions.repository.entity.DataScopeSubConditionExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class DataScopeSubConditionSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    public String countByExample(DataScopeSubConditionExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("data_scope_sub_condition");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    public String deleteByExample(DataScopeSubConditionExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("data_scope_sub_condition");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    public String insertSelective(DataScopeSubCondition record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("data_scope_sub_condition");
        
        if (record.getConditionsId() != null) {
            sql.VALUES("conditions_id", "#{conditionsId,jdbcType=BIGINT}");
        }
        
        if (record.getValueTypeId() != null) {
            sql.VALUES("value_type_id", "#{valueTypeId,jdbcType=BIGINT}");
        }
        
        if (record.getField() != null) {
            sql.VALUES("field", "#{field,jdbcType=VARCHAR}");
        }
        
        if (record.getOperation() != null) {
            sql.VALUES("`operation`", "#{operation,jdbcType=VARCHAR}");
        }
        
        if (record.getIndex() != null) {
            sql.VALUES("`index`", "#{index,jdbcType=SMALLINT}");
        }
        
        if (record.getValue() != null) {
            sql.VALUES("`value`", "#{value,jdbcType=VARCHAR}");
        }
        
        if (record.getLink() != null) {
            sql.VALUES("link", "#{link,jdbcType=TINYINT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    public String selectByExample(DataScopeSubConditionExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("conditions_id");
        sql.SELECT("value_type_id");
        sql.SELECT("field");
        sql.SELECT("`operation`");
        sql.SELECT("`index`");
        sql.SELECT("`value`");
        sql.SELECT("link");
        sql.FROM("data_scope_sub_condition");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        DataScopeSubCondition record = (DataScopeSubCondition) parameter.get("record");
        DataScopeSubConditionExample example = (DataScopeSubConditionExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("data_scope_sub_condition");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getConditionsId() != null) {
            sql.SET("conditions_id = #{record.conditionsId,jdbcType=BIGINT}");
        }
        
        if (record.getValueTypeId() != null) {
            sql.SET("value_type_id = #{record.valueTypeId,jdbcType=BIGINT}");
        }
        
        if (record.getField() != null) {
            sql.SET("field = #{record.field,jdbcType=VARCHAR}");
        }
        
        if (record.getOperation() != null) {
            sql.SET("`operation` = #{record.operation,jdbcType=VARCHAR}");
        }
        
        if (record.getIndex() != null) {
            sql.SET("`index` = #{record.index,jdbcType=SMALLINT}");
        }
        
        if (record.getValue() != null) {
            sql.SET("`value` = #{record.value,jdbcType=VARCHAR}");
        }
        
        if (record.getLink() != null) {
            sql.SET("link = #{record.link,jdbcType=TINYINT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("data_scope_sub_condition");
        
        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("conditions_id = #{record.conditionsId,jdbcType=BIGINT}");
        sql.SET("value_type_id = #{record.valueTypeId,jdbcType=BIGINT}");
        sql.SET("field = #{record.field,jdbcType=VARCHAR}");
        sql.SET("`operation` = #{record.operation,jdbcType=VARCHAR}");
        sql.SET("`index` = #{record.index,jdbcType=SMALLINT}");
        sql.SET("`value` = #{record.value,jdbcType=VARCHAR}");
        sql.SET("link = #{record.link,jdbcType=TINYINT}");
        
        DataScopeSubConditionExample example = (DataScopeSubConditionExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(DataScopeSubCondition record) {
        SQL sql = new SQL();
        sql.UPDATE("data_scope_sub_condition");
        
        if (record.getConditionsId() != null) {
            sql.SET("conditions_id = #{conditionsId,jdbcType=BIGINT}");
        }
        
        if (record.getValueTypeId() != null) {
            sql.SET("value_type_id = #{valueTypeId,jdbcType=BIGINT}");
        }
        
        if (record.getField() != null) {
            sql.SET("field = #{field,jdbcType=VARCHAR}");
        }
        
        if (record.getOperation() != null) {
            sql.SET("`operation` = #{operation,jdbcType=VARCHAR}");
        }
        
        if (record.getIndex() != null) {
            sql.SET("`index` = #{index,jdbcType=SMALLINT}");
        }
        
        if (record.getValue() != null) {
            sql.SET("`value` = #{value,jdbcType=VARCHAR}");
        }
        
        if (record.getLink() != null) {
            sql.SET("link = #{link,jdbcType=TINYINT}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, DataScopeSubConditionExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}