package com.xforceplus.ultraman.permissions.repository;

import com.xforceplus.ultraman.permissions.repository.entity.FieldScope;
import com.xforceplus.ultraman.permissions.repository.entity.FieldScopeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface FieldScopeRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_scope
     *
     * @mbg.generated
     */
    @SelectProvider(type=FieldScopeSqlProvider.class, method="countByExample")
    long countByExample(FieldScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_scope
     *
     * @mbg.generated
     */
    @DeleteProvider(type=FieldScopeSqlProvider.class, method="deleteByExample")
    int deleteByExample(FieldScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_scope
     *
     * @mbg.generated
     */
    @Delete({
        "delete from field_scope",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_scope
     *
     * @mbg.generated
     */
    @Insert({
        "insert into field_scope (`role`, tenant, ",
        "entity, field)",
        "values (#{role,jdbcType=VARCHAR}, #{tenant,jdbcType=VARCHAR}, ",
        "#{entity,jdbcType=VARCHAR}, #{field,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(FieldScope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_scope
     *
     * @mbg.generated
     */
    @InsertProvider(type=FieldScopeSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(FieldScope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_scope
     *
     * @mbg.generated
     */
    @SelectProvider(type=FieldScopeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="role", property="role", jdbcType=JdbcType.VARCHAR),
        @Result(column="tenant", property="tenant", jdbcType=JdbcType.VARCHAR),
        @Result(column="entity", property="entity", jdbcType=JdbcType.VARCHAR),
        @Result(column="field", property="field", jdbcType=JdbcType.VARCHAR)
    })
    List<FieldScope> selectByExample(FieldScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_scope
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, `role`, tenant, entity, field",
        "from field_scope",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="role", property="role", jdbcType=JdbcType.VARCHAR),
        @Result(column="tenant", property="tenant", jdbcType=JdbcType.VARCHAR),
        @Result(column="entity", property="entity", jdbcType=JdbcType.VARCHAR),
        @Result(column="field", property="field", jdbcType=JdbcType.VARCHAR)
    })
    FieldScope selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_scope
     *
     * @mbg.generated
     */
    @UpdateProvider(type=FieldScopeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") FieldScope record, @Param("example") FieldScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_scope
     *
     * @mbg.generated
     */
    @UpdateProvider(type=FieldScopeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") FieldScope record, @Param("example") FieldScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_scope
     *
     * @mbg.generated
     */
    @UpdateProvider(type=FieldScopeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(FieldScope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_scope
     *
     * @mbg.generated
     */
    @Update({
        "update field_scope",
        "set `role` = #{role,jdbcType=VARCHAR},",
          "tenant = #{tenant,jdbcType=VARCHAR},",
          "entity = #{entity,jdbcType=VARCHAR},",
          "field = #{field,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(FieldScope record);
}