package com.xforceplus.ultraman.permissions.rule.repository.entity;

import java.io.Serializable;

public class DataScopeSubCondition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.conditions_id
     *
     * @mbg.generated
     */
    private Long conditionsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.value_type_id
     *
     * @mbg.generated
     */
    private Long valueTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.index
     *
     * @mbg.generated
     */
    private Short index;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_sub_condition.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.id
     *
     * @return the value of data_scope_sub_condition.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.id
     *
     * @param id the value for data_scope_sub_condition.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.conditions_id
     *
     * @return the value of data_scope_sub_condition.conditions_id
     *
     * @mbg.generated
     */
    public Long getConditionsId() {
        return conditionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.conditions_id
     *
     * @param conditionsId the value for data_scope_sub_condition.conditions_id
     *
     * @mbg.generated
     */
    public void setConditionsId(Long conditionsId) {
        this.conditionsId = conditionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.value_type_id
     *
     * @return the value of data_scope_sub_condition.value_type_id
     *
     * @mbg.generated
     */
    public Long getValueTypeId() {
        return valueTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.value_type_id
     *
     * @param valueTypeId the value for data_scope_sub_condition.value_type_id
     *
     * @mbg.generated
     */
    public void setValueTypeId(Long valueTypeId) {
        this.valueTypeId = valueTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.operator
     *
     * @return the value of data_scope_sub_condition.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.operator
     *
     * @param operator the value for data_scope_sub_condition.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.index
     *
     * @return the value of data_scope_sub_condition.index
     *
     * @mbg.generated
     */
    public Short getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.index
     *
     * @param index the value for data_scope_sub_condition.index
     *
     * @mbg.generated
     */
    public void setIndex(Short index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_sub_condition.value
     *
     * @return the value of data_scope_sub_condition.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_sub_condition.value
     *
     * @param value the value for data_scope_sub_condition.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_sub_condition
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", conditionsId=").append(conditionsId);
        sb.append(", valueTypeId=").append(valueTypeId);
        sb.append(", operator=").append(operator);
        sb.append(", index=").append(index);
        sb.append(", value=").append(value);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}