package com.xforceplus.ultraman.permissions.rule.repository.entity;

import java.io.Serializable;

public class DataScopeConditions implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_conditions.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_conditions.data_scope_id
     *
     * @mbg.generated
     */
    private Long dataScopeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_scope_conditions.column
     *
     * @mbg.generated
     */
    private String column;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_scope_conditions
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_conditions.id
     *
     * @return the value of data_scope_conditions.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_conditions.id
     *
     * @param id the value for data_scope_conditions.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_conditions.data_scope_id
     *
     * @return the value of data_scope_conditions.data_scope_id
     *
     * @mbg.generated
     */
    public Long getDataScopeId() {
        return dataScopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_conditions.data_scope_id
     *
     * @param dataScopeId the value for data_scope_conditions.data_scope_id
     *
     * @mbg.generated
     */
    public void setDataScopeId(Long dataScopeId) {
        this.dataScopeId = dataScopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_scope_conditions.column
     *
     * @return the value of data_scope_conditions.column
     *
     * @mbg.generated
     */
    public String getColumn() {
        return column;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_scope_conditions.column
     *
     * @param column the value for data_scope_conditions.column
     *
     * @mbg.generated
     */
    public void setColumn(String column) {
        this.column = column == null ? null : column.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_scope_conditions
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dataScopeId=").append(dataScopeId);
        sb.append(", column=").append(column);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}