package com.xforceplus.ultraman.permissions.rule.repository.entity;

import java.io.Serializable;

public class RolePermissions implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.scope_id
     *
     * @mbg.generated
     */
    private Long scopeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.scope_type
     *
     * @mbg.generated
     */
    private Byte scopeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_permissions
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.id
     *
     * @return the value of role_permissions.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.id
     *
     * @param id the value for role_permissions.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.role_id
     *
     * @return the value of role_permissions.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.role_id
     *
     * @param roleId the value for role_permissions.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.scope_id
     *
     * @return the value of role_permissions.scope_id
     *
     * @mbg.generated
     */
    public Long getScopeId() {
        return scopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.scope_id
     *
     * @param scopeId the value for role_permissions.scope_id
     *
     * @mbg.generated
     */
    public void setScopeId(Long scopeId) {
        this.scopeId = scopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.scope_type
     *
     * @return the value of role_permissions.scope_type
     *
     * @mbg.generated
     */
    public Byte getScopeType() {
        return scopeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.scope_type
     *
     * @param scopeType the value for role_permissions.scope_type
     *
     * @mbg.generated
     */
    public void setScopeType(Byte scopeType) {
        this.scopeType = scopeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", scopeId=").append(scopeId);
        sb.append(", scopeType=").append(scopeType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}