apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "xplat-data-permissions.fullname" . }}-configmap
    labels:
        app: {{ template "xplat-data-permissions.name" . }}
        chart: {{ template "xplat-data-permissions.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
data:
    application.yml: |
        server:
          port: 8080
        management:
          health:
            redis:
              enabled: false
          endpoints:
            enabled-by-default: false
            web:
              exposure:
                include: "*"
          endpoint:
            health:
              enabled: true
            shutdown:
              enabled: true
            info:
              enabled: true
            prometheus:
              enabled: true
        grpc:
          enabled: {{ .Values.grpc.enabled }}
          port: 8206
          maxInboundMetadataBytes: {{int .Values.grpc.maxInboundMetadataBytes }}
          maxInboundMessageBytes: {{int .Values.grpc.maxInboundMessageBytes }}
          heartbeatIntervalSeconds: {{ .Values.grpc.heartbeatIntervalSeconds }}
          heartbeatTimeoutSeconds: {{ .Values.grpc.heartbeatTimeoutSeconds }}
        # 线程池.
        executor:
          maxTaskSize: {{ .Values.executor.maxTaskSize }}
          {{- if .Values.executor.maxWorkerSize }}
          maxWorkerSize: {{ .Values.executor.maxWorkerSize }}
          {{- end }}
        spring:
          application:
            name: "xplat-data-permissions"
          cache:
            type: GENERIC
            cache-names: rule
          datasource:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://{{ .Values.jdbc.host | default "127.0.0.1" }}:{{ .Values.jdbc.port | default "3306" }}/{{ .Values.jdbc.dbname }}?useUnicode=true&characterEncoding=utf8&socketTimeout={{int .Values.jdbc.connection.readTimeoutSeconds }}&autoReconnect=true&failOverReadOnly=false
            username: {{ .Values.jdbc.userName | default "root" }}
            password: {{ .Values.jdbc.password | default "root" }}
            hikari:
              connection-test-query: "select 1"
              connection-timeout: {{int .Values.jdbc.pool.connectionTimeoutSeconds | default "1000" }}
              validation-timeout: {{ .Values.jdbc.connection.readTimeoutSeconds | default "3000" }}
              maximum-pool-size: {{ .Values.jdbc.pool.maxSize | default "3" }}
        j2cache:
          config-location: file:/xplat/j2cache/j2cache.properties
          open-spring-cache: true
          cache-clean-mode: {{ .Values.cache.cleanMode }}
          l2-cache-open: {{ .Values.cache.l2.enabled }}
          redis-client: lettuce
        logging:
          level:
            root: {{ .Values.logger.level }}
            io:
              opencensus: INFO
    j2cache.properties: |
        {{- if .Values.cache.l2.enabled }}
        j2cache.broadcast = net.oschina.j2cache.cache.support.redis.SpringRedisPubSubPolicy
        {{- else }}
        j2cache.broadcast = none
        {{- end }}
        j2cache.L1.provider_class = caffeine
        j2cache.L2.provider_class = net.oschina.j2cache.cache.support.redis.SpringRedisProvider
        j2cache.L2.config_section = lettuce
        j2cache.sync_ttl_to_redis = true
        j2cache.default_cache_null_object = true
        j2cache.serialization = kryo
        caffeine.region.default = {{ .Values.cache.l1.size | default "10000" }}, {{ .Values.cache.l1.ttl | default "30d" }}
        lettuce.storage = {{ .Values.cache.l2.redis.storage | default "hash" }}
        lettuce.channel = {{ .Values.cache.l2.redis.channel | default "dataPermissions" }}
        lettuce.scheme = {{ .Values.cache.l2.redis.scheme | default "redis" }}
        lettuce.hosts = {{ .Values.cache.l2.redis.host }}:{{ .Values.cache.l2.redis.port | default "6379" }}
        {{- if .Values.cache.l2.redis.password }}
        lettuce.password = {{ .Values.cache.l2.redis.password }}
        {{- end }}
        lettuce.database = {{ .Values.cache.l2.redis.database | default "0" }}
        lettuce.maxTotal = {{ .Values.cache.l2.redis.pool.max | default "10" }}
        lettuce.maxIdle = {{ .Values.cache.l2.redis.pool.maxIdle | default "6" }}
        lettuce.minIdle = {{ .Values.cache.l2.redis.pool.minIdle | default "3" }}
        lettuce.timeout = {{ .Values.cache.l2.redis.timeout | default "1000" }}
