apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ template "xplat-data-permissions.fullname" . }}
    labels:
        app: {{ template "xplat-data-permissions.name" . }}
        chart: {{ template "xplat-data-permissions.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: {{ template "xplat-data-permissions.name" . }}
            release: {{ .Release.Name }}
    template:
        metadata:
            labels:
                app: {{ template "xplat-data-permissions.name" . }}
                release: {{ .Release.Name }}
                {{- with .Values.annotations }}
            annotations:
{{ toYaml . | indent 14 }}
            {{- end }}
        spec:
            containers:
                - name: {{ .Chart.Name }}
                  image: "{{ .Values.image.repository }}:{{ template "image.tag" . }}"
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  lifecycle:
                    preStop:
                      exec:
                        command: ["/bin/sh","-c","curl","-X","POST","http://127.0.0.1:8080/actuator/shutdown"]
                  env:
                    - name: JVM_HEAP_PERCENTAGE
                      value: "60"
                  command: ["java"]
                  args:
                    - -jar
                    {{- range .Values.jvm }}
                    - {{ . }}
                    {{- end }}
                    - /xplat/xplat-data-permissions.jar
                    - --spring.config.location=/xplat/application.yml
                  ports:
                      - name: http-metrics
                        containerPort: 8080
                        protocol: TCP
                      - name: grpc
                        containerPort: 8206
                        protocol: TCP
                  volumeMounts:
                      - mountPath: /xplat/application.yml
                        name: config
                        subPath: application.yml
                      - mountPath: /xplat/j2cache/j2cache.properties
                        name: config
                        subPath: j2cache.properties
                  livenessProbe:
                      httpGet:
                          scheme: HTTP
                          path: /actuator/health
                          port: 8080
                      initialDelaySeconds: 30
                      periodSeconds: 60
                      failureThreshold: 3
                      timeoutSeconds: 30
                  readinessProbe:
                      httpGet:
                          scheme: HTTP
                          path: /actuator/health
                          port: 8080
                      initialDelaySeconds: 3
                      periodSeconds: 6
                      failureThreshold: 3
                      timeoutSeconds: 30
                  resources:
{{ toYaml .Values.resources | indent 20 }}
                {{- if .Values.affinity }}
                {{- with .Values.affinity }}
            affinity:
{{ toYaml . | indent 14 }}
                {{- end }}
                {{- else }}
            volumes:
                - name: config
                  configMap:
                      name: {{ template "xplat-data-permissions.fullname" . }}-configmap
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        - topologyKey: "kubernetes.io/hostname"
                          labelSelector:
                              matchLabels:
                                  app: {{ template "xplat-data-permissions.name" . }}
                                  release: {{ .Release.Name }}
                {{- end }}
                {{- with .Values.nodeSelector }}
            nodeSelector:
{{ toYaml . | indent 14 }}
                {{- end }}
                {{- with .Values.tolerations }}
            tolerations:
{{ toYaml . | indent 14 }}
        {{- end }}
